import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/page.module.css';
import Navbar from '../features/Navbar';
import { Contact } from '../features/Contact';
import { Calendly } from '../components/Calendly';
import { Schedule } from '../features/Schedule';

const inter = Inter({ subsets: ['latin'] });

export default function ContactPage() {
	return (
		<>
			<Head>
				<title>Daniel Patton</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<nav>
				<Navbar />
			</nav>
			<main className={styles.main}>
				<Contact
					phone={'(404) 483-9426'}
					email={'me@danielpatton.dev'}
					location={'Greenville, SC'}
					linkedin={'https://www.linkedin.com/in/daniel-patton-developer'}
					github={'https://github.com/dpatton1992'}
					discord={'dpatton#1992'}
				/>
			</main>
		</>
	);
}
