'use client';

import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/page.module.css';
import Navbar from '@/app/components/Navbar';
import Hero from '@/app/components/Hero';
import Bio from '@/app/components/Bio';
import Resume from '@/app/components/Resume';
import ScrollLink from './components/ScrollLink';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Daniel Patton</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<nav>
				<Navbar />
			</nav>
			<main className={styles.main}>
				<section id="hero" className={styles.section}>
					<Hero />
				</section>
				<section id="bio" className={styles.section}>
					<Bio />
				</section>
				<section id="resume" className={styles.section}>
					<Resume />
				</section>
			</main>
		</>
	);
}
